cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'coreutils'
brew 'findutils'
brew 'openssl'
brew 'nvm'
brew 'httpie'
brew 'git'
brew 'youtube-dl'
brew 'jenv'
brew 'leiningen'

cask 'alfred'
cask 'iterm2'
cask 'dropbox'
cask 'skype'
cask 'flux'
cask 'visual-studio-code'
cask 'macvim'
cask 'mono-mdk'
cask 'google-chrome'
cask 'slack'
cask 'vlc'
cask 'spectacle'
cask 'caffeine'
cask 'screenhero'
cask 'sqlectron'
cask 'java'
