#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                              \
    external_bar                all:40:0     \
    mouse_follows_focus         on           \
    focus_follows_mouse         off          \
    window_placement            second_child \
    window_topmost              off          \
    window_shadow               off          \
    window_animation_duration   0.00         \
    window_opacity_duration     0.00         \
    active_window_opacity       0.90         \
    normal_window_opacity       0.50         \
    window_opacity              off          \
    insert_feedback_color       0xaad75f5f   \
    active_window_border_color  0xBF775759   \
    normal_window_border_color  0x7f353535   \
    window_border_width         4            \
    window_border_radius        12           \
    window_border_blur          on           \
    window_border_hidpi         on           \
    window_border               on           \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 2            \
    left_padding                2            \
    right_padding               2            \
    bottom_padding              2            \
    window_gap                  10           \
    layout                      bsp          \
    mouse_modifier              ctrl         \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

yabai -m space 1 --label web
yabai -m space 2 --label term
yabai -m space 3 --label notes
yabai -m space 4 --label apps
yabai -m space 5 --label social
yabai -m space 6 --label fun

yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor|ExpressVPN|Docker Desktop)$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Arc$" space=web
yabai -m rule --add app="^iTerm2$" space=term
yabai -m rule --add app="^Obsidian$" space=notes
yabai -m rule --add app="^(WhatsApp|Messages|Discord)$" space=social

