#!/usr/bin/env bash

alias chrome='open -a /Applications/Google\ Chrome.app'
alias rider='open -na "Rider.app" --args nosplash "$@"'

alias sudo='sudo '
alias vim='nvim'

alias DT='tee ~/Desktop/terminalOutput.txt'

alias updatesw='sudo softwareupdate -i -a'
alias fixcamera='sudo killall VDCAssistant'

# delete all merged branches in repository
alias gcb='git branch --merged| egrep -v (^*|master) | xargs git branch -d'

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

alias dos2lf='dos2unix `find ./ -type f`'

alias dnsflush='dscacheutil -flushcache'

alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl; sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# Files being opened
alias files.open='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep open'
# Files used, anywhere on the filesystem
alias files.usage='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep'
# Files in use in the Users directory
alias files.usage.user='sudo fs_usage -e -f filesystem|grep -v CACHE_HIT|grep -v grep|grep Users'

# ip address commands
alias ip.all="ip addr | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"
alias ip.dns="dig +short myip.opendns.com @resolver1.opendns.com"
alias ip.http='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'
alias ip.vpn='if [ "$(ip.dns)" == "$SERVER_EXT_IP" ]; then; echo "\033[0;32mUsing VPN\033[0m"; else; echo "\033[0;31m[!!!] Not Using VPN\033[0m"; fi'
alias ports='netstat -tulnp'

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Show network connections
alias network.connections='lsof -l -i +L -R -V'
alias network.established='lsof -l -i +L -R -V | grep ESTABLISHED'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Copy and paste and prune the usless newline
alias pbcopynn='tr -d "\n" | pbcopy'

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

alias jsonfix="pbpaste | jq . | pbcopy"

alias lookbusy="cat /dev/urandom | hexdump -C | grep \"34 32\""

alias ls="ls --color=auto"

alias k="kubectl"
